version: "3.8"
services:
  cockroachdb:
    container_name: node_1
    image: cockroachdb/cockroach:v20.2.7
    volumes:
      - ./database-data/node_1:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
    - "26257:26257"
    - "9000:8080"
  consul:
    image: consul
    ports:
      - "8500:8500"
  rabbitmq:
    image: rabbitmq:3.7.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
